### ISSUE TITLE
Additional dependencies for Debian/Ubuntu install

### ISSUE THREAD

**Issue by SebastianKG** [memgraph/mgmigrate#13]
I couldn't install on Ubuntu, and I was receiving this error:

```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_TYPE_INCLUDE_DIR) (found
  version "14.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPostgreSQL.cmake:247 (find_package_handle_standard_args)
  CMakeLists.txt:47 (find_package)
```

Then I looked at CMakeLists.txt, looked into what `find_package(PostgreSQL REQUIRED)` actually does (it runs a CMake built-in script to find Postgres) and encountered this StackOverflow post about the same problem with that script: https://stackoverflow.com/a/40027295.

In short, the user should also be asked to `apt-get install libpq-dev postgresql-server-dev-all`.

**Comment by gitbuda** [comment]
There is a PR fixing exactly that #11 😄 I can actually merge that right away 💪

**Comment by gitbuda** [comment]
Done by merging #11
